setwd("/Users/ramosm18/Desktop/ExData_Plotting1")
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subsetdata <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(subsetdata$Date, subsetdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
subset_gap <- as.numeric(subsetdata$Global_active_power)
Submetering1 <- as.numeric(subsetdata$Sub_metering_1)
Submetering2 <- as.numeric(subsetdata$Sub_metering_2)
Submetering3 <- as.numeric(subsetdata$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime, Submetering1, type="l", xlab="" , ylab="Energy sub metering")
lines(datetime, Submetering2, type="l", col="red")
lines(datetime, Submetering3, type="l", col="blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
